import { Check, Mail, MapPin, Phone } from "lucide-react";
import QRCode from "react-qr-code";
import { AcademicShell } from "@/components/AcademicShell";

const vcard = "BEGIN:VCARD\nVERSION:3.0\nFN:Nicholas Vanderschantz\nEMAIL:nicholas.vanderschantz@waikato.ac.nz\nTEL:078384000\nADR:;;G.2.15;University of Waikato;;;\nEND:VCARD";

export default function ContactDetailsPage() {
  return (
    <AcademicShell title="Contact details" description="Keep your information up to date so visitors can easily get in touch.">
      <div className="grid gap-5 xl:grid-cols-[minmax(0,3fr)_minmax(300px,2fr)]"><form className="border border-[#d9e1e7] bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Information visitors can see</h2><p className="mt-1 text-[#526a84]">Choose what to share on the office display and contact link.</p><div className="mt-6 grid gap-5"><label className="font-semibold">Name<input className="mt-2 block w-full border border-[#b9c8d6] p-3 font-normal" defaultValue="Nicholas Vanderschantz" /></label><label className="font-semibold">Email<input className="mt-2 block w-full border border-[#b9c8d6] p-3 font-normal" type="email" defaultValue="nicholas.vanderschantz@waikato.ac.nz" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="font-semibold">Phone<input className="mt-2 block w-full border border-[#b9c8d6] p-3 font-normal" defaultValue="07 838 4000" /></label><label className="font-semibold">Office<input className="mt-2 block w-full border border-[#b9c8d6] p-3 font-normal" defaultValue="G.2.15" /></label></div><label className="font-semibold">Public message <span className="font-normal text-[#526a84]">(optional)</span><textarea className="mt-2 block min-h-28 w-full resize-none border border-[#b9c8d6] p-3 font-normal" defaultValue="Drop in during office hours - I am always happy to chat about your ideas, questions, or academic plans." maxLength={200} /></label></div><div className="mt-5 flex items-center gap-5"><button type="button" className="bg-[#087a54] px-6 py-3 font-semibold text-white hover:bg-[#066543]">Save details</button><p className="flex items-center gap-2 text-[#087a54]"><Check size={20} /> Saved</p></div></form><aside className="border border-[#d9e1e7] bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Outside your office</h2><div className="mt-5 border border-[#cbd8d3] bg-[#f5faf8] p-5"><p className="text-2xl font-bold text-[#076443]">Nicholas Vanderschantz</p><div className="mt-5 space-y-3 text-[#35566f]"><p className="flex items-center gap-3 break-all"><Mail size={19} /> nicholas.vanderschantz@waikato.ac.nz</p><p className="flex items-center gap-3"><Phone size={19} /> 07 838 4000</p><p className="flex items-center gap-3"><MapPin size={19} /> Office G.2.15</p></div><div className="mx-auto mt-6 w-fit bg-white p-3"><QRCode value={vcard} size={130} fgColor="#08243f" /></div><p className="mt-2 text-center text-sm text-[#526a84]">Scan to save contact</p></div></aside></div>
    </AcademicShell>
  );
}
